# Generated by Django 4.2.2 on 2023-08-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conted_vies',
            new_name='count_views',
        ),
    ]
